version: 2.1

executors:
  default:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7-stretch-node

commands:
  restore_yarn:
    steps:
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
  save_yarn:
    steps:
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

jobs:
  install:
    executor:
      name: default
    steps:
      - checkout
      - restore_yarn
      - run: yarn
      - save_yarn
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./*

  # test:
  #   executor:
  #     name: default
  #   steps:
  #     - attach_workspace:
  #         at: ~/project
  #     - run: yarn test

  build:
    executor:
      name: default
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn generate
      - persist_to_workspace:
          root: ~/project
          paths:
            - dist

  deploy:
    executor:
      name: default
    steps:
      - attach_workspace:
          at: ~/project
      - run: sudo pip install awscli
      - run: aws s3 sync ./dist/ s3://inductor.dev --exact-timestamps --delete --exclude "*" --include "*.html" --cache-control no-store
      - run: aws s3 sync ./dist/ s3://inductor.dev --exact-timestamps --delete --exclude "*" --include "*.js" --cache-control max-age=31536000
      - run: aws cloudfront create-invalidation --distribution-id $CF_DIST_ID --paths "/*"

workflows:
  test-deploy:
    jobs:
      - install
      # - test:
      #     requires:
      #       - install
      - build:
          <<: *filter_only_master
          requires:
            - install
            # - test  filters:
          filters:
            branches:
              only: master

      - deploy:
          <<: *filter_only_master
          requires:
            - install
            # - test
            - build
          filters:
            branches:
              only: master
